[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
backgroundColor = "#060913"
secondaryBackgroundColor = "#04060b"
primaryColor = "#3b82f6"
textColor = "#e2e8f0"
font = "sans serif"
